<TextQuestionScreen>:
    MDCard:
        size_hint: .8, .8
        pos_hint: {"center_x": .5, "center_y": .5}
        padding: "10dp"

        ScrollView:
            size_hint: 1, 0.6
            pos_hint: {"top" : 1}
            GridLayout:
                id: sets_layout
                cols: 1
                size_hint_y: None
                height: self.minimum_height
                spacing: "10dp"
                padding: "10dp"
